// Generated by jextract

package de.schmizzolin.vish.signal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("sa_handler"),
        JAVA_INT.withName("sa_mask"),
        JAVA_INT.withName("sa_flags")
    ).withName("sigaction");
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(sigaction.sa_handler.class, "apply", constants$0.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$0.const$1
    );
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("sa_handler"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("sa_mask"));
}


