// Generated by jextract

package de.schmizzolin.vish.signal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("sa_flags"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sigaction",
        constants$1.const$1
    );
}


