// Generated by jextract

package de.schmizzolin.vish.signal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class simple_signal_h  {
}


