/*
 * Copyright Michael Hartmeier, https://github.com/mlhartme/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** Origianlly generated by jextract from errno.h */

package de.schmizzolin.vish.filesystem;

import foreign.fuse.fuse_h;

public record Attr(short mode, long size, long lastModified) {
    public static Attr file(long size, long lastModified) {
        return new Attr((short) (fuse_h.S_IFREG() | 0600), size, lastModified);
    }
    public static Attr directory(long modified) {
        return new Attr((short) (fuse_h.S_IFDIR() | 0700), 0, modified);
    }
}


