// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(fuse_operations.reserved00.class, "apply", constants$27.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$27.const$5
    );
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("reserved00"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.reserved01.class, "apply", constants$27.const$5);
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("reserved01"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.renamex.class, "apply", constants$26.const$3);
}


