// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final VarHandle const$0 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("setchgtime"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.setcrtime.class, "apply", constants$5.const$4);
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("setcrtime"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.chflags.class, "apply", constants$20.const$4);
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("chflags"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.setattr_x.class, "apply", constants$5.const$4);
}


