// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(fuse_operations.truncate.class, "apply", constants$11.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$11.const$5
    );
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("truncate"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.utime.class, "apply", constants$5.const$4);
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("utime"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.open.class, "apply", constants$5.const$4);
}


