// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final VarHandle const$0 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("exchange"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.getxtimes.class, "apply", constants$7.const$0);
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("getxtimes"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.setbkuptime.class, "apply", constants$5.const$4);
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("setbkuptime"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.setchgtime.class, "apply", constants$5.const$4);
}


