// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(fuse_operations.poll.class, "apply", constants$4.const$0);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$4.const$0
    );
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("poll"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(fuse_operations.write_buf.class, "apply", constants$25.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$25.const$3
    );
}


