// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(fuse_operations.unlink.class, "apply", constants$4.const$2);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$4.const$2
    );
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("unlink"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.rmdir.class, "apply", constants$4.const$2);
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("rmdir"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.symlink.class, "apply", constants$5.const$4);
}


