// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final VarHandle const$0 = constants$0.const$4.varHandle(MemoryLayout.PathElement.groupElement("tv_nsec"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("st_dev"),
        JAVA_SHORT.withName("st_mode"),
        JAVA_SHORT.withName("st_nlink"),
        JAVA_LONG.withName("st_ino"),
        JAVA_INT.withName("st_uid"),
        JAVA_INT.withName("st_gid"),
        JAVA_INT.withName("st_rdev"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_atimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_mtimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_ctimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_birthtimespec"),
        JAVA_LONG.withName("st_size"),
        JAVA_LONG.withName("st_blocks"),
        JAVA_INT.withName("st_blksize"),
        JAVA_INT.withName("st_flags"),
        JAVA_INT.withName("st_gen"),
        JAVA_INT.withName("st_lspare"),
        MemoryLayout.sequenceLayout(2, JAVA_LONG).withName("st_qspare")
    ).withName("stat");
    static final VarHandle const$2 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_dev"));
    static final VarHandle const$3 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_mode"));
    static final VarHandle const$4 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_nlink"));
    static final VarHandle const$5 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_ino"));
}


