// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final VarHandle const$0 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("symlink"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.rename.class, "apply", constants$5.const$4);
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("rename"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.link.class, "apply", constants$5.const$4);
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("link"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.chmod.class, "apply", constants$8.const$2);
}


