// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final VarHandle const$0 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("init"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.destroy.class, "apply", constants$4.const$4);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$4.const$4
    );
    static final VarHandle const$3 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("destroy"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.access.class, "apply", constants$20.const$4);
}


