// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$7.const$4
    );
    static final VarHandle const$1 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("mknod"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.mkdir.class, "apply", constants$8.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$8.const$2
    );
    static final VarHandle const$5 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("mkdir"));
}


