// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final VarHandle const$0 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("write"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.statfs.class, "apply", constants$5.const$4);
    static final VarHandle const$2 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("statfs"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.flush.class, "apply", constants$5.const$4);
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("flush"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.release.class, "apply", constants$5.const$4);
}


