// Generated by jextract

package foreign.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_fill_dir_t.class, "apply", constants$5.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$5.const$0
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("getattr"),
        RuntimeHelper.POINTER.withName("readlink"),
        RuntimeHelper.POINTER.withName("getdir"),
        RuntimeHelper.POINTER.withName("mknod"),
        RuntimeHelper.POINTER.withName("mkdir"),
        RuntimeHelper.POINTER.withName("unlink"),
        RuntimeHelper.POINTER.withName("rmdir"),
        RuntimeHelper.POINTER.withName("symlink"),
        RuntimeHelper.POINTER.withName("rename"),
        RuntimeHelper.POINTER.withName("link"),
        RuntimeHelper.POINTER.withName("chmod"),
        RuntimeHelper.POINTER.withName("chown"),
        RuntimeHelper.POINTER.withName("truncate"),
        RuntimeHelper.POINTER.withName("utime"),
        RuntimeHelper.POINTER.withName("open"),
        RuntimeHelper.POINTER.withName("read"),
        RuntimeHelper.POINTER.withName("write"),
        RuntimeHelper.POINTER.withName("statfs"),
        RuntimeHelper.POINTER.withName("flush"),
        RuntimeHelper.POINTER.withName("release"),
        RuntimeHelper.POINTER.withName("fsync"),
        RuntimeHelper.POINTER.withName("setxattr"),
        RuntimeHelper.POINTER.withName("getxattr"),
        RuntimeHelper.POINTER.withName("listxattr"),
        RuntimeHelper.POINTER.withName("removexattr"),
        RuntimeHelper.POINTER.withName("opendir"),
        RuntimeHelper.POINTER.withName("readdir"),
        RuntimeHelper.POINTER.withName("releasedir"),
        RuntimeHelper.POINTER.withName("fsyncdir"),
        RuntimeHelper.POINTER.withName("init"),
        RuntimeHelper.POINTER.withName("destroy"),
        RuntimeHelper.POINTER.withName("access"),
        RuntimeHelper.POINTER.withName("create"),
        RuntimeHelper.POINTER.withName("ftruncate"),
        RuntimeHelper.POINTER.withName("fgetattr"),
        RuntimeHelper.POINTER.withName("lock"),
        RuntimeHelper.POINTER.withName("utimens"),
        RuntimeHelper.POINTER.withName("bmap"),
        MemoryLayout.paddingLayout(8),
        RuntimeHelper.POINTER.withName("ioctl"),
        RuntimeHelper.POINTER.withName("poll"),
        RuntimeHelper.POINTER.withName("write_buf"),
        RuntimeHelper.POINTER.withName("read_buf"),
        RuntimeHelper.POINTER.withName("flock"),
        RuntimeHelper.POINTER.withName("fallocate"),
        RuntimeHelper.POINTER.withName("reserved00"),
        RuntimeHelper.POINTER.withName("reserved01"),
        RuntimeHelper.POINTER.withName("renamex"),
        RuntimeHelper.POINTER.withName("statfs_x"),
        RuntimeHelper.POINTER.withName("setvolname"),
        RuntimeHelper.POINTER.withName("exchange"),
        RuntimeHelper.POINTER.withName("getxtimes"),
        RuntimeHelper.POINTER.withName("setbkuptime"),
        RuntimeHelper.POINTER.withName("setchgtime"),
        RuntimeHelper.POINTER.withName("setcrtime"),
        RuntimeHelper.POINTER.withName("chflags"),
        RuntimeHelper.POINTER.withName("setattr_x"),
        RuntimeHelper.POINTER.withName("fsetattr_x")
    ).withName("fuse_operations");
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.getattr.class, "apply", constants$5.const$4);
}


